"""empty message

Revision ID: 0931acd9e651
Revises: 10732ef297c3
Create Date: 2019-07-25 14:41:23.313725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0931acd9e651'
down_revision = '10732ef297c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['people_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diseases_stages')
    op.drop_table('diseases_categories')
    op.add_column('medicine', sa.Column('disease_stage_id', sa.Integer(), nullable=True))
    op.drop_constraint('medicine_stage_id_fkey', 'medicine', type_='foreignkey')
    op.create_foreign_key(None, 'medicine', 'disease_stage', ['disease_stage_id'], ['id'])
    op.drop_column('medicine', 'stage_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medicine', type_='foreignkey')
    op.create_foreign_key('medicine_stage_id_fkey', 'medicine', 'stage', ['stage_id'], ['id'])
    op.drop_column('medicine', 'disease_stage_id')
    op.create_table('diseases_categories',
    sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['people_category.id'], name='diseases_categories_category_id_fkey')
    )
    op.create_table('diseases_stages',
    sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name='diseases_stages_stage_id_fkey')
    )
    op.drop_table('disease_stage')
    op.drop_table('disease_category')
    # ### end Alembic commands ###
