"""empty message

Revision ID: 10732ef297c3
Revises: 8841078b198b
Create Date: 2019-07-25 14:24:13.356960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10732ef297c3'
down_revision = '8841078b198b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases_categories',
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['people_category.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], )
    )
    op.drop_constraint('disease_people_category_id_fkey', 'disease', type_='foreignkey')
    op.drop_column('disease', 'people_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disease', sa.Column('people_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('disease_people_category_id_fkey', 'disease', 'people_category', ['people_category_id'], ['id'])
    op.drop_table('diseases_categories')
    # ### end Alembic commands ###
